### ISSUE TITLE
Add "how to cite"

### ISSUE THREAD

**Issue by Athospd** [skeydan/Deep-Learning-and-Scientific-Computing-with-R-torch#10]
Hi, Sygrid, hope you are well. I would like to request a copy-pasting version of how to cite this book.

Thank you for this book, by the way, I'm learning.

**Comment by skeydan** [comment]
Hi Athos,
great hearing from you! And happy to hear you find it useful.
Well I guess it should be like this:

```
@book{keydana2023deep,
  title={Deep Learning and Scientific Computing with R torch},
  author={Keydana, Sigrid},
  year={2023},
  publisher={CRC Press}
}
```

Ciao,
Sigrid
