### ISSUE TITLE
1:num_iterations range in for loops

### ISSUE THREAD

**Issue by wbzyl** [skeydan/Deep-Learning-and-Scientific-Computing-with-R-torch#5]
The book contains several loops where I noticed the following pattern:

```r
for (i in 1:num_iterations) {
  #...
  if (i %% 100 == 0) {
    cat("Value is: ", as.numeric(value), "\n")
  }
  #...
}
```

The first text is printed after 100 iterations for `i==100`.
Nothing is printed on the very first iteration.

I propose to change the range to `0:num_iterations`:

```r
for (i in 0:num_iterations) {
  #...
  if (i %% 100 == 0) {
    cat("Value is: ", as.numeric(value), "\n")
  }
  #...
```

I think that the most interesting things usually happen at the beginning.

--Włodek Bzyl

**Comment by skeydan** [comment]
Thanks for the suggestion! I can see what you mean. In general though, this will depend on the task, the dataset, etc. ...

In your work, you will surely want to look at what is most informative for you. 

In the book though, it is in general more about explaining how things work, and to provide template-like code (for different types of applications) that should adapt straightforwardly to a user's demands, than to reach top performance on some [benchmark, toy, ...] dataset.

**Comment by wbzyl** [comment]
> In your work, you will surely want to look at what is most informative for you.

In subsections 10.2.1 and 10.2.2, I've noticed how you approach things.

I like your approach and the way explain things.
Thanks for the book.

**Comment by skeydan** [comment]
Thanks, I'm happy you like it!
