### ISSUE TITLE
any resources about NLP from you?

### ISSUE THREAD

**Issue by jlxAtNovozymes** [skeydan/Deep-Learning-and-Scientific-Computing-with-R-torch#7]
Hi, When I read the chapter 17, it says this book won't cover NLP, I wanna ask BTW do you have any plan to write a book or a series of blogs about NLP with torch for R? haha, really looking forward to :)

**Comment by skeydan** [comment]
Hi, thanks for asking. A book, that's rather unlikely - a series of blog posts, we'll see :-)
