### ISSUE TITLE
If this sounds like magic, there is a simple means to make the magic go away.

### ISSUE THREAD

**Issue by wbzyl** [skeydan/Deep-Learning-and-Scientific-Computing-with-R-torch#8]
### Understanding convnet – simpler way to make the magic go away

In subsection 15.2.2.1, you wrote:

> Namely, a simple way to find out about tensor shapes at any stage in a network is to comment all subsequent actions in `forward()`, and call the modified model.

I'm thinking of a simpler solution. Print the model first:
```r
img <- torch_randn(1, 1, 64, 64)
model <- convnet()
model
```
```
An `nn_module` containing 30,211 parameters.

── Modules ────────────────────────────────
• conv1: <nn_conv2d> #160 parameters
• conv2: <nn_conv2d> #4,640 parameters
• conv3: <nn_conv2d> #18,496 parameters
• output: <nn_linear> #6,915 parameters
```

Then, if it would be possible to cut out the submodel, let's cut it out.
```r
submodel <- model['conv2']
submodel(img)$size()
#> 1 32 29 29
```

I'm guessing the code, of course, but maybe there's a way to replace the line of code `submodel <- model['conv2']`.

**Comment by skeydan** [comment]
Hi Włodek,

I'm really happy the book seems to be triggering a lot of creativity :-)

However, please understand that I cannot answer all questions about deep learning in this repository. 
I'd recommend asking in Posit community forum, where there are lots of friendly users around :-)

https://community.rstudio.com/c/ml/15

**Comment by wbzyl** [comment]
OK. 
Thanks.
